name:                haskell-project
version:             1.0.0.20
github:              "rohit-singh-42/haskell-project"
license:             BSD-3-Clause
author:              
    - Rohit Singh (240204707)
    - Basak Ertugrul (240685593)
    - Parul Anand (240774152)

maintainer:          
    - r.singh@se24.qmul.ac.uk
    - b.ertugrul@se24.qmul.ac.uk
    - ec24193@qmul.ac.uk
copyright:           "2024 Rohit Singh, Basak Ertugrul & Parul Anand"

extra-source-files:
- README.md
- CHANGELOG.md
- AUTHORS.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rohit-singh-42/haskell-project#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- http-types
- case-insensitive
- sqlite-simple
- bytestring
- aeson
- time
- blaze-html

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-project

tests:
  haskell-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-project
